some build updates

diff --git a/image/scripts/dependencies_check b/image/scripts/dependencies_check
--- a/image/scripts/dependencies_check
+++ b/image/scripts/dependencies_check
@@ -19,33 +19,32 @@
 
 dependencies_check()
 {
-	local depfile deps missing
+    local depfile deps missing
 
-	for depfile in "$@"; do
-		if [[ -e "$depfile" ]]; then
-			deps="$(sed -f "${SCRIPT_DIR}/remove-comments.sed" < "${BASE_DIR}/depends")"
+    for depfile in "$@"; do
+        if [[ -e "$depfile" ]]; then
+            deps="$(sed -f "${SCRIPT_DIR}/remove-comments.sed" < "${BASE_DIR}/depends")"
 
-		fi
-		for dep in $deps; do
-			if ! hash "${dep%:*}" 2>/dev/null; then
-				missing="${missing:+$missing }${dep#*:}"
-			fi
-		done
-	done
+        fi
+        for dep in $deps; do
+            if ! hash "${dep%:*}" 2>/dev/null; then
+                missing="${missing:+$missing }${dep#*:}"
+            fi
+        done
+    done
 
-	if [[ "$missing" ]]; then
-		echo "Required dependencies not installed"
-		echo
-		echo "This can be resolved on Debian/Raspbian systems by installing:"
-		echo "$missing"
-		false
-	fi
+    if [[ "$missing" ]]; then
+        echo "Required dependencies not installed"
+        echo
+        echo "This can be resolved on Debian/Raspbian systems by installing:"
+        echo "$missing"
+        false
+    fi
 
-
-	if ! grep -q "/proc/sys/fs/binfmt_misc" /proc/mounts; then
-		echo "Module binfmt_misc not loaded in host"
-		echo "Please run:"
-		echo "  sudo modprobe binfmt_misc"
-		exit 1
-	fi
+    if ! grep -q "/proc/sys/fs/binfmt_misc" /proc/mounts; then
+        echo "Module binfmt_misc not loaded in host"
+        echo "Please run:"
+        echo "  sudo modprobe binfmt_misc"
+        exit 1
+    fi
 }
